# -*- coding: utf-8 -*-
"""데이터 관리 및 저장 /판다스 기본 사용법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sgx72zuxsbu2nSPwN29LZOyQXNyhsmd

1. txt 파일로 저장
*  변수 = open("파일 이름","오픈 형식"): 파일을 해당형식으로 열어주는 방법 
  *   오픈 형식:
        1.  w : write 모드, 새로운 파일을 쓸 때 사용
        2.  r : read 모드, 파일로부터 데이터를 읽고 싶을 때 사용
        3.  a : append 모드, 파일에 데이터를 추가하고 싶을 때 사용
 
 
 * 변수.close() : 열린 파일을 닫는 방법(파일을 닫지 않으면 어딘가에 열린채로 유지)
"""

f = open("test01.txt","w") #파일 생성

f.write("test memo1") #내용 입력1
f.write("\n")
f.write("test memo2") #내용 입력2

f.close()

"""2.csv(Comma Separated Value)로 저장


*   csv: 콤마로 구분되는 값들의 모음
*   csv 값들의 열 구분 -> 콤마(,)
*   csv 값들의 행 구분 -> 엔터(\n)





"""

f = open("programLanguage.csv",'w')

#활용 데이터
name = ['name','python','Java','R','C']
rate = ['rate','상','상','중','하']

for i in range(len(name)):
  print(i)

#데이터 파일에 입력
for i in range(len(name)):
  f.write(name[i]+','+rate[i]+'\n')

f.close()



"""# 2-2. pandas 활용"""

import pandas as pd

data = [
        [1,2,3,4,5],
        ['a','b','c','d','e']
]

data

dataframe= pd.DataFrame(data,columns = ['col1','col2','col3','col4','col5'])

dataframe

dataframe['col_test']=1

dataframe

dataframe.to_csv("test02.csv", index=False)
dataframe.to_csv("test02_1.csv")

"""# 3. excel로 저장

# 3-1. 오픈파이엑셀 활용


*   파이썬으로 엑셀을 다룰 수 있게 해주는 라이브러리
"""

import openpyxl #pip install openpyxl

wb = openpyxl.Workbook()

sheet = wb.active
sheet['A1'] = 'Test OpenPyXL'
sheet.cell(row=3, column=1).value = 'TEST'

name = ['PYTHON','JAVA','R','C']
sheet.append(name)

wb.save("test03.xlsx")

"""# 3-2. 판다스 활용"""

dataFrame.to_excel("test03.xlsx", sheet_name = "pandas_excel")

"""# 판다스 기본 사용법 익히기"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# 1.데이터 오브젝트 생성하기"""

s = pd.Series([1,3,5,np.nan,6,8])

s

type(s)

dates = pd.date_range('20130101', periods=6)

dates

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=["A","B","C","D"])

df

dates = pd.date_range('20130101', periods=6)
a = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

dates_str = ['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06']
b = pd.DataFrame(np.random.randn(6,4), index=dates_str, columns=list('ABCD'))

a

a.head(3)

b

b['B'] = [str(i) for i in b['B'].tolist()]   #B에 있는 값들을 list로 가져와서 각각의 값들을 string으로 바꿔준다
b['C'] = [round(i,1) for i in b['C'].tolist()]   #C의 칼럼들을 가져와서 소수점 첫째자리에서 반올림 해준다.

b

